target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'lottie-ios'
  pod 'PromisesSwift'
  pod 'Swinject', '~> 2.6.2'
  pod 'SwinjectAutoregistration'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'KMPNativeCoroutinesAsync', '0.11.1'
end